# Generated by Django 2.2.5 on 2019-09-04 06:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', ckeditor.fields.RichTextField(default='S/D', verbose_name='Descripcion')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Catalogo/', verbose_name='Imagen')),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria', verbose_name='Categoria')),
                ('id_Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
