# Generated by Django 2.2.5 on 2019-09-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nombre'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
    ]
