# Generated by Django 2.2.5 on 2019-10-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_equipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('identificador', 'cat', 'orden')},
        ),
    ]
