# Generated by Django 2.2.5 on 2019-10-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20191003_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Equipo Didactico', 'verbose_name_plural': 'Equipos Didacticos'},
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_Marca',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id_Marca',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Marca', verbose_name='Marca'),
        ),
    ]
