# Generated by Django 2.2.5 on 2019-11-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20191004_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
    ]
