# Generated by Django 2.2.5 on 2019-09-19 00:38

from django.db import migrations, models
import django.db.models.deletion
import movimientos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_no', models.CharField(default=movimientos.models.get_rand_string, help_text='Se asignara el numero de referencia', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Dato o No. de Referencia')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Se tomara la fecha automatica de creacion', verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, help_text='Se tomara la fecha automatica de creacion', verbose_name='Hora')),
                ('module', models.CharField(max_length=50, verbose_name='Modulo')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Send', to='registration.Perfil', verbose_name='Asignado a')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Create', to='registration.Perfil', verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
    ]
