# Generated by Django 2.2.5 on 2019-09-19 00:46

from django.db import migrations, models
import movimientos.models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='id_no',
            field=models.CharField(default=movimientos.models.get_rand_string, help_text='Se asignara automaticamente un ID', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Dato o No. de Referencia'),
        ),
    ]
