# Generated by Django 2.2.5 on 2019-09-19 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('movimientos', '0002_auto_20190918_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_Asignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('ubicacion', models.CharField(help_text='Debo de corregir y anclar bien la ubicacion', max_length=75, verbose_name='Ubicacion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Monto')),
                ('id_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Asignacion', verbose_name='Ingreso')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material_Asignado',
                'verbose_name_plural': 'Material_Asignados',
            },
        ),
    ]
