# Generated by Django 2.2.5 on 2019-09-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_auto_20190919_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'verbose_name': 'Devolucion', 'verbose_name_plural': 'Devoluciones'},
        ),
    ]
