# Generated by Django 2.2.5 on 2019-09-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0005_auto_20190919_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='module',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='asig_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_Create_Dev', to='movimientos.Asignacion', verbose_name='Creado Por'),
            preserve_default=False,
        ),
    ]
