# Generated by Django 2.2.5 on 2019-09-22 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0006_auto_20190920_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='asig_id',
            field=models.ForeignKey(help_text='La devolucion debe conicidir con una Asignacion', on_delete=django.db.models.deletion.CASCADE, to='movimientos.Asignacion', verbose_name='Ref. Asignacion'),
        ),
    ]
