# Generated by Django 2.2.5 on 2019-09-26 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0008_recepccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='assigned_to',
            field=models.ForeignKey(help_text='Se asignara automaticamente a unusuario encargado de bodega', on_delete=django.db.models.deletion.CASCADE, related_name='User_Send', to='registration.Perfil', verbose_name='Asignado a'),
        ),
    ]
