# Generated by Django 2.2.5 on 2019-09-26 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('movimientos', '0009_auto_20190925_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Send', to='registration.Perfil', verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='asig_id',
            field=models.ForeignKey(help_text='La devolucion debe conicidir con una Asignacion asicomo los elementos deben cuadrar', on_delete=django.db.models.deletion.CASCADE, to='movimientos.Asignacion', verbose_name='Ref. Asignacion'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='assigned_to',
            field=models.ForeignKey(help_text='Se asignara automaticamente a un  usuario encargado de bodega', on_delete=django.db.models.deletion.CASCADE, related_name='User_Send_Dev', to='registration.Perfil', verbose_name='Asignado a'),
        ),
        migrations.CreateModel(
            name='Material_Devuelto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('U', 'Utilizado'), ('C', 'Consumido')], default='Bueno', max_length=2)),
                ('id_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Devolucion', verbose_name='Ingreso')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material Devuelto',
                'verbose_name_plural': 'Materiales Devueltos',
            },
        ),
    ]
