# Generated by Django 2.2.5 on 2019-09-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0010_auto_20190925_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_devuelto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='material_devuelto',
            name='estado',
        ),
        migrations.AddField(
            model_name='material_devuelto',
            name='buenos',
            field=models.PositiveIntegerField(default=0, help_text='Material que no se utilizo', verbose_name='Sin Utilizar'),
        ),
        migrations.AddField(
            model_name='material_devuelto',
            name='consumidos',
            field=models.PositiveIntegerField(default=0, help_text='Material que fue consumido en total y no es posible reutilizar', verbose_name='Consumidos'),
        ),
        migrations.AddField(
            model_name='material_devuelto',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='material_devuelto',
            name='usados',
            field=models.PositiveIntegerField(default=0, help_text='Material que se utilizo y se puede seguir usando', verbose_name='Utilizados'),
        ),
    ]
