# Generated by Django 2.2.5 on 2019-10-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0011_auto_20190925_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_devuelto',
            name='total',
        ),
        migrations.AddField(
            model_name='material_devuelto',
            name='totalXD',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
