# Generated by Django 2.2.5 on 2019-10-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0014_auto_20191001_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_devuelto',
            name='consumidos',
        ),
        migrations.RemoveField(
            model_name='material_devuelto',
            name='usados',
        ),
        migrations.AddField(
            model_name='material_devuelto',
            name='desechados',
            field=models.PositiveIntegerField(default=0, help_text='Material que en practica fue dechado', verbose_name='Desechados'),
        ),
        migrations.AddField(
            model_name='material_devuelto',
            name='transformados',
            field=models.PositiveIntegerField(default=0, help_text='Material que se utilizo para practica o se convirtio en modelo didactico', verbose_name='Trasformados o utilizados'),
        ),
    ]
