# Generated by Django 2.2.5 on 2019-10-02 19:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0017_auto_20191001_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='devuelto',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='comentario',
            field=ckeditor.fields.RichTextField(default='S/C', help_text='Ingrese un comentario de porque la devolucion,y como fue que se utilizaron los materiales o equipospara enriquecer la informacion agregada', verbose_name='Comentario'),
        ),
    ]
