# Generated by Django 2.2.5 on 2019-10-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0018_auto_20191002_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='devuelto',
        ),
    ]
