# Generated by Django 2.2.5 on 2019-10-10 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_delete_material_detalle_egreso'),
        ('movimientos', '0020_equipo_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_devuelto',
            name='id_devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Devolucion', verbose_name='Devolucion'),
        ),
        migrations.CreateModel(
            name='Equipo_Devuelto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Bno.', 'Bueno'), ('Mlo.', 'Malo'), ('Rlr.', 'Con Daño')], default='Bueno', max_length=4)),
                ('comentarios', models.TextField(verbose_name='Comentarios')),
                ('id_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Devolucion', verbose_name='Devolucion')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Equipo_Ingreso', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Equipo_Asignado',
                'verbose_name_plural': 'Equipo_Asignados',
            },
        ),
    ]
