# Generated by Django 2.2.5 on 2019-10-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0021_auto_20191009_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo_devuelto',
            options={'verbose_name': 'Equipo Devuelto', 'verbose_name_plural': 'Equipos Devueltos'},
        ),
    ]
