# Generated by Django 2.2.5 on 2019-11-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0024_auto_20191102_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='is_dev',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
