# Generated by Django 2.2.5 on 2019-11-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0026_auto_20191103_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo_asignado',
            options={'verbose_name': 'Equipo Asignado', 'verbose_name_plural': 'Equipo Asignados'},
        ),
        migrations.AddField(
            model_name='equipo_asignado',
            name='is_it_disp',
            field=models.BooleanField(default=False, verbose_name='Esta disponible'),
        ),
    ]
