# Generated by Django 2.2.5 on 2019-11-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0027_auto_20191103_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo_asignado',
            name='is_it_disp',
        ),
    ]
