# Generated by Django 2.2.5 on 2019-09-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mi_Perfil',
            fields=[
            ],
            options={
                'verbose_name': 'Mi Perfil',
                'verbose_name_plural': 'Mi Perfil',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registration.perfil',),
        ),
    ]
