# Generated by Django 2.2.5 on 2019-09-04 17:47

import django.core.validators
from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puesto',
            field=models.CharField(blank=True, max_length=25, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Ingrese solamente numeros', regex='^[0-9]*$'), registration.models.val_tel], verbose_name='Telefono'),
        ),
    ]
