# Generated by Django 2.2.5 on 2019-11-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_mi_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='puesto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='Es Instructor'),
        ),
    ]
