# Generated by Django 4.2 on 2024-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_alter_entry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialentrydetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount'),
        ),
    ]
