# Generated by Django 4.2 on 2024-03-20 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movements', '0003_alter_materialentrydetail_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('reference', models.CharField(help_text='\n        Field for the Document No. that will\n        serve as a reference for the purchase\n        or donation\n    ', max_length=250, verbose_name='Reference')),
                ('state', models.BooleanField(default=False, verbose_name='Available')),
                ('description', models.TextField(default='S/D', verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'EntryMaterial',
                'verbose_name_plural': 'Entries Materials',
            },
        ),
        migrations.AlterField(
            model_name='materialentrydetail',
            name='id_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movements.entrymaterial'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
