# Generated by Django 5.0.3 on 2024-03-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='image'),
        ),
    ]
