# Generated by Django 4.2 on 2024-03-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_alter_brand_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/imgs/', verbose_name='Imagen'),
        ),
    ]
