# Generated by Django 2.2.5 on 2019-09-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
