# Generated by Django 2.2.5 on 2019-09-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20190909_1856'),
        ('asignacion', '0002_asignacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_Asig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('ubicacion', models.CharField(help_text='Debo de corregir y anclar bien la ubicacion', max_length=75, verbose_name='Ubicacion')),
                ('ref_ingreso', models.CharField(editable=False, help_text='Referencia segun el ingreso', max_length=75, verbose_name='Ref.')),
                ('id_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.Asignacion', verbose_name='Ingreso')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Base_Detalle',
                'verbose_name_plural': 'Base_Detalles',
            },
        ),
    ]
