# Generated by Django 2.2.5 on 2019-09-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0003_material_asig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material_asig',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.RemoveField(
            model_name='material_asig',
            name='ref_ingreso',
        ),
        migrations.RemoveField(
            model_name='material_asig',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='material_asig',
            name='modulo',
            field=models.CharField(default=1, help_text='Debo de corregir y anclar bien la ubicacion', max_length=75, verbose_name='Modulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material_asig',
            name='ref_Asignacion',
            field=models.CharField(default=1, editable=False, help_text='Referencia La Asignacion Padre', max_length=75, verbose_name='Ref_Asignacion.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material_asig',
            name='id_asig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.Asignacion', verbose_name='No. de Asignacion'),
        ),
    ]
