# Generated by Django 2.2.5 on 2019-09-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0004_auto_20190913_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_asig',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='material_asig',
            name='ref_Asignacion',
        ),
        migrations.AddField(
            model_name='material_asig',
            name='ref_ingreso',
            field=models.CharField(default=1, editable=False, help_text='Referencia segun el ingreso', max_length=75, verbose_name='Ref.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material_asig',
            name='ubicacion',
            field=models.CharField(default=1, help_text='Debo de corregir y anclar bien la ubicacion', max_length=75, verbose_name='Ubicacion'),
            preserve_default=False,
        ),
    ]
