# Generated by Django 2.2.5 on 2019-09-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0006_auto_20190913_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_asig',
            name='modulo',
            field=models.CharField(help_text='Debo de corregir y anclar bien la ubicacion', max_length=75, null=True, verbose_name='Modulo'),
        ),
        migrations.AddField(
            model_name='material_asig',
            name='ref_asignacion',
            field=models.CharField(editable=False, help_text='Referencia segun el ingreso', max_length=75, null=True, verbose_name='Ref_Asignacion.'),
        ),
    ]
