# Generated by Django 2.2.5 on 2019-09-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Se tomara la fecha automatica de creacion', verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, help_text='Se tomara la fecha automatica de creacion', verbose_name='Hora')),
                ('referencia', models.CharField(help_text='Indique el No. de Documento que servira como referencia en la compra o donacion del material que ingresara a Bodega..!', max_length=75, verbose_name='No. de Referencia')),
                ('estado', models.BooleanField(default=False, verbose_name='Dispobible')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Perfil', verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Material_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('ubicacion', models.CharField(help_text='Debo de corregir y anclar bien la ubicacion', max_length=75, verbose_name='Ubicacion')),
                ('ref_ingreso', models.CharField(editable=False, help_text='Referencia segun el ingreso', max_length=75, verbose_name='Ref.')),
                ('id_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Ingreso', verbose_name='Ingreso')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Detalle de Material',
                'verbose_name_plural': 'Detalle de Materiales',
            },
        ),
    ]
