# Generated by Django 2.2.5 on 2019-09-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Se tomara la fecha automatica de creacion', verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, help_text='Se tomara la fecha automatica de creacion', verbose_name='Hora')),
                ('referencia', models.CharField(help_text='Indique el No. de Documento que servira como referencia en la compra o donacion del material que ingresara a Bodega..!', max_length=75, verbose_name='No. de Referencia')),
                ('disponible', models.BooleanField(default=False, verbose_name='Dispobible')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Perfil', verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
    ]
