# Generated by Django 2.2.5 on 2019-09-04 01:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='S/D', verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='material',
            name='id_Categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='id_Marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Marca', verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Material/'),
        ),
        migrations.AddField(
            model_name='material',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
