# Generated by Django 2.2.5 on 2019-10-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipo_ingreso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo_Ingreso',
        ),
    ]
