# Generated by Django 2.2.5 on 2019-09-08 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_asignacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name': 'Asignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
    ]
