# Generated by Django 2.2.5 on 2019-09-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20190908_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Perfil', verbose_name='Creado Por'),
        ),
    ]
