# Generated by Django 2.2.5 on 2019-09-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('inventario', '0004_auto_20190908_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.Perfil', verbose_name='Creado Por'),
            preserve_default=False,
        ),
    ]
