# Generated by Django 2.2.5 on 2019-10-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20191003_1152'),
        ('inventario', '0004_equipo_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBE', models.CharField(max_length=15, verbose_name='IBE')),
                ('categ', models.PositiveIntegerField(verbose_name='Categoria')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unidad')),
                ('ubicacion', models.CharField(help_text='Debo de corregir y anclar bien la ubicacion', max_length=75, verbose_name='Ubicacion')),
                ('ref_ingreso', models.CharField(editable=False, help_text='Referencia segun el ingreso', max_length=75, verbose_name='Ref.')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Equipo', verbose_name='Equipo')),
                ('id_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Ingreso', verbose_name='Ingreso')),
            ],
            options={
                'verbose_name': 'Detalle de Equipo',
                'verbose_name_plural': 'Detalle de Equipos',
            },
        ),
    ]
