# Generated by Django 2.2.5 on 2019-10-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_equipo_detalle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo_Detalle',
        ),
    ]
