# Generated by Django 2.2.5 on 2019-09-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_asignacion_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='module',
            field=models.CharField(default=1, max_length=50, verbose_name='Modulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Perfil', verbose_name='Asignar a'),
        ),
    ]
