# Generated by Django 2.2.5 on 2019-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_delete_equipo_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_ingreso',
            name='orden',
            field=models.CharField(max_length=5, verbose_name='Orden'),
        ),
    ]
