# Generated by Django 2.2.5 on 2019-09-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20190908_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Perfil', verbose_name='Asignado a'),
        ),
    ]
