# Generated by Django 2.2.5 on 2019-09-08 17:25

from django.db import migrations, models
import django.db.models.deletion
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20190908_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='asig_id',
            field=models.CharField(default=inventario.models.Asignacion.get_rand_string, max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='ingreso_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='inventario.Ingreso'),
        ),
    ]
