# Generated by Django 2.2.5 on 2019-09-14 16:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20190910_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material_detalle',
            options={'ordering': ['id_ingreso__fecha'], 'verbose_name': 'Detalle de Material', 'verbose_name_plural': 'Detalle de Materiales'},
        ),
        migrations.AddField(
            model_name='ingreso',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='S/D', help_text='Descripcion del Ingreso o la Referencia de INgreso', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='referencia',
            field=models.CharField(help_text='Indique el No. de Documento que servira como Referencia en la compra, donacion o ingreso del materialBodega de Electricidad..!', max_length=75, verbose_name='Dato o No. de Referencia'),
        ),
    ]
