# Generated by Django 2.2.5 on 2019-09-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20190908_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='asig_id',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
