# Generated by Django 2.2.5 on 2019-10-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20191004_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_ingreso',
            name='modelo',
            field=models.CharField(max_length=25, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo_ingreso',
            name='serie',
            field=models.CharField(max_length=25, verbose_name='Serie'),
        ),
    ]
