# Generated by Django 2.2.5 on 2019-09-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20190908_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='asig_id',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='ingreso_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.Ingreso'),
        ),
    ]
