# Generated by Django 2.2.5 on 2019-09-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20190914_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='descripcion',
            field=models.CharField(default='S/D', help_text='Descripcion del Ingreso o la Referencia de INgreso', max_length=100, verbose_name='Descripcion'),
        ),
    ]
