# Generated by Django 2.2.5 on 2019-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20191004_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_ingreso',
            name='ibe',
            field=models.CharField(help_text='El no de Inventario IBE debe seguir el siguiente formato X-XXX-XXXXX', max_length=15, verbose_name='No. de Inventario IBE'),
        ),
        migrations.AlterField(
            model_name='equipo_ingreso',
            name='modelo',
            field=models.CharField(blank=True, max_length=25, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo_ingreso',
            name='serie',
            field=models.CharField(blank=True, max_length=25, verbose_name='Serie'),
        ),
    ]
