# Generated by Django 2.2.5 on 2019-09-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20190908_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='no_asignacion',
            field=models.CharField(default=1, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='ingreso_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='inventario.Ingreso'),
        ),
    ]
