# Generated by Django 2.2.5 on 2019-10-04 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20191004_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_ingreso',
            name='ibe',
            field=models.CharField(help_text='El no de Inventario IBE debe seguir el siguiente formato X-XXX-XXXXX', max_length=15, validators=[django.core.validators.RegexValidator(message='El Formato debe coincidir', regex='^[I][/-][0-9]{3}[/-][0-9]{5}$')], verbose_name='No. de Inventario IBE'),
        ),
    ]
