# Generated by Django 2.2.5 on 2019-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20191004_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='is_baja',
            field=models.BooleanField(default=False),
        ),
    ]
