# Generated by Django 2.2.5 on 2019-09-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20190908_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='referencia',
            field=models.CharField(help_text='Indique el No. de Documento que servira como Referencia en la compra, donacion o ingreso del material Bodega de Electricidad..!', max_length=75, verbose_name='Dato o No. de Referencia'),
        ),
    ]
