# Generated by Django 2.2.5 on 2019-10-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_material_detalle_egreso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material_Detalle_Egreso',
        ),
    ]
