# Generated by Django 2.2.5 on 2019-10-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_delete_material_detalle_egreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_for_asig',
            fields=[
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.equipo_ingreso',),
        ),
    ]
