# Generated by Django 2.2.5 on 2019-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_auto_20191102_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo_ingreso',
            name='is_it_disp',
            field=models.BooleanField(default=False, verbose_name='Esta disponible'),
        ),
    ]
