# Generated by Django 2.2.5 on 2019-11-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_equipo_ingreso_is_it_disp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_ingreso',
            name='is_it_disp',
            field=models.BooleanField(default=True, verbose_name='Esta disponible'),
        ),
    ]
