# Generated by Django 2.2.5 on 2019-11-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20191103_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo_ingreso',
            name='is_it_disp',
        ),
    ]
