# Generated by Django 2.2.5 on 2019-10-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nombre'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
